# Generated by Django 4.2.5 on 2023-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tag_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFirstTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=100)),
                ('totalvotes', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
